---
dependency:
  name: galaxy

driver:
  name: docker

lint:
  name: yamllint

platforms:
  - name: ansible-role-cm-centos-max
    image: centos:8
    dockerfile: ../default/Dockerfile.j2

provisioner:
  name: ansible
  playbooks:
    converge: ../cm-max/playbook.yml
  lint:
    name: ansible-lint

scenario:
  name: centos-max-cm-max

verifier:
  name: testinfra
  directory: ../cm-max/tests
  lint:
    name: flake8
